# Generated by Django 2.1.3 on 2018-12-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planes1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(blank=True, max_length=100, null=True)),
                ('p', models.CharField(blank=True, max_length=200, null=True)),
                ('o', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes1',
                'managed': False,
            },
        ),
    ]
