# Generated by Django 2.1.3 on 2018-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s', models.CharField(blank=True, max_length=400, null=True)),
                ('p', models.CharField(blank=True, max_length=400, null=True)),
                ('o', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Planes',
                'verbose_name_plural': 'Planes',
                'db_table': 'planes1',
                'default_related_name': 'planes',
            },
        ),
    ]
