# Generated by Django 2.1.3 on 2018-12-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planes',
            table='planes1',
        ),
    ]
