# Generated by Django 2.1.3 on 2018-12-04 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('competencia', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'competencias',
                'default_related_name': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='Contenidos',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.CharField(max_length=2)),
                ('contenido', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenidos',
                'default_related_name': 'contenidos',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('cod', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, max_length=1500)),
                ('pre_requisitos', models.CharField(blank=True, max_length=300)),
                ('edicion', models.CharField(default=1, max_length=3)),
                ('oferta', models.CharField(max_length=20)),
                ('tematica', models.CharField(blank=True, max_length=60)),
                ('fecha_inscripcion', models.DateField(default=datetime.datetime.now)),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now)),
                ('esfuerzo_estimado', models.CharField(default=1, max_length=2)),
                ('duracion', models.CharField(default=1, max_length=2)),
                ('link', models.CharField(default='http://opencampus.utpl.edu.ec/', max_length=100)),
                ('institucion', models.CharField(choices=[('UTPL', 'UTPL'), ('Otro', 'Otro')], default='UTPL', max_length=5)),
                ('archivado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'default_related_name': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nivel_academico', models.CharField(choices=[('T', 'Nivel Técnico'), ('TN', 'Tercer Nivel'), ('CN', 'Cuarto Nivel')], default='TN', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('resumen', models.TextField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docentes',
                'default_related_name': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Retos',
            fields=[
                ('id_reto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_reto', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_fin', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion', models.CharField(max_length=400)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='cursosHandler.Cursos')),
            ],
            options={
                'verbose_name': 'Reto',
                'verbose_name_plural': 'Retos',
                'db_table': 'retos',
                'default_related_name': 'retos',
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursosHandler.Docentes'),
        ),
        migrations.AddField(
            model_name='contenidos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='cursosHandler.Cursos'),
        ),
        migrations.AddField(
            model_name='competencias',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='cursosHandler.Cursos'),
        ),
    ]
