# Generated by Django 2.1.2 on 2018-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosHandler', '0002_auto_20181112_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='resumen',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
