# Generated by Django 2.1.2 on 2018-11-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosHandler', '0003_auto_20181112_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
