# Generated by Django 2.1.2 on 2018-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosHandler', '0005_auto_20181112_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='tematica',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
