# Generated by Django 2.1.2 on 2018-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosHandler', '0006_auto_20181112_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='cod',
            field=models.CharField(max_length=15),
        ),
    ]
