# Generated by Django 2.1.2 on 2018-11-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosHandler', '0007_auto_20181112_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='cod',
            field=models.CharField(max_length=20),
        ),
    ]
